name = "example"
type = "executable"

lib-c = true

[profile.fb]
backend = "llvm"
output-ir = true

[profile.debug]
output-ir = true

[profile.release]
output-ir = true

[[dependency]]
path = "foo"

[[dependency]]
url = "https://github.com/fireball-lang/std.git"
revision = "04c9fe6854449b626c8b5c4a06446139ee00d8b7"
