name: Setup LLVM
description: Install C3 LLVM toolchain

inputs:
  version:
    description: LLVM release version
    required: true
    default: "22.1.8"

runs:
  using: composite
  steps:
    - name: Cache LLVM
      id: llvm-cache
      uses: actions/cache@v6
      with:
        path: llvm
        key: llvm-tools-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}

    - name: Download LLVM
      if: steps.llvm-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -euo pipefail

        case "$RUNNER_OS-$RUNNER_ARCH" in
          Linux-X64)
            asset="llvm-tools-${{ inputs.version }}-linux-amd64.tar.gz"
            ;;
          macOS-ARM64)
            asset="llvm-tools-${{ inputs.version }}-macos-aarch64.tar.gz"
            ;;
          Windows-X64)
            asset="llvm-tools-${{ inputs.version }}-windows-amd64.zip"
            ;;
          *)
            echo "Unsupported platform: $RUNNER_OS-$RUNNER_ARCH"
            exit 1
            ;;
        esac

        url="https://github.com/fireball-lang/llvm/releases/download/v${{ inputs.version }}/$asset"
        echo "Downloading LLVM: $url"
        curl -fL "$url" -o "$asset"

        mkdir -p llvm
        if [[ "$asset" == *.zip ]]; then
          7z x "$asset" -ollvm
        else
          tar xf "$asset" -C llvm
        fi

        rm $asset

    - name: Add LLVM to PATH
      shell: bash
      run: |
        echo "${{ github.workspace }}/llvm" >> "$GITHUB_PATH"
