name: Setup LLVM
description: Install LLVM toolchain

inputs:
  version:
    description: LLVM release version
    required: true
  os:
    description: Operating system
    required: true
  arch:
    description: Architecture
    required: true
  path:
    description: Where to extract the LLVM tools
    required: true

runs:
  using: composite
  steps:
    - name: Cache LLVM
      id: llvm-cache
      uses: actions/cache@v6
      with:
        path: ${{ path }}
        key: "llvm-${{ inputs.version }}-${{ inputs.os }}-${{ inputs.arch }}"

    - name: Download LLVM
      if: steps.llvm-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -euo pipefail

        # Download LLVM tools
        case "${{ inputs.os }}" in
          windows)
            asset="llvm-tools-${{ inputs.version }}-${{ inputs.os }}-${{ inputs.arch }}.zip"
            ;;
          *)
            asset="llvm-tools-${{ inputs.version }}-${{ inputs.os }}-${{ inputs.arch }}.tar.gz"
            ;;
        esac

        url="https://github.com/fireball-lang/llvm/releases/download/v${{ inputs.version }}/$asset"
        echo "Downloading LLVM: $url"
        curl -fL "$url" -o "$asset"

        # Extract them into provided path
        mkdir -p "${{ inputs.path }}"

        if [[ "$asset" == *.zip ]]; then
          7z x "$asset" -o"${{ inputs.path }}"
        else
          tar xf "$asset" -C "${{ inputs.path }}"
        fi

        # Remove archive and add path to PATH
        rm $asset
        echo "${{ github.workspace }}/${{ inputs.path }}" >> "$GITHUB_PATH"
