id = "fireball"
name = "Fireball"
version = "0.1.0"
schema_version = 1
authors = ["MineGame159 <petulko08@gmail.com>"]
description = "Fireball language support"
repository = "https://github.com/MineGame159/fireball"

[grammars.fireball]
repository = "https://github.com/MineGame159/tree-sitter-fireball"
rev = "9c6343c131fd24b631726908defbf89758e365f6"
