id = "fireball"
name = "Fireball"
version = "0.1.0"
schema_version = 1
authors = ["MineGame159 <petulko08@gmail.com>"]
description = "Fireball language support"
repository = "https://github.com/MineGame159/fireball"

[grammars.fireball]
repository = "https://github.com/fireball-lang/tree-sitter-fireball"
rev = "37cd39c27bf0a6498a86617d90bfa9438240bf6c"

[language_servers.fireball]
name = "Fireball"
languages = ["Fireball"]
