id = "fireball"
name = "Fireball"
version = "0.1.0"
schema_version = 1
authors = ["MineGame159 <petulko08@gmail.com>"]
description = "Fireball language support"
repository = "https://github.com/MineGame159/fireball"

[grammars.fireball]
repository = "https://github.com/fireball-lang/tree-sitter-fireball"
rev = "8ef51221fb15100a326f974e6aaa00af5d4dcbed"

[language_servers.fireball]
name = "Fireball"
languages = ["Fireball"]
