name: Build

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Build
        run: |
          cd src
          go build -o ../fireball ./cmd

      - name: Cache fireball
        uses: actions/cache/save@v3
        with:
          path: fireball
          key: ${{ runner.os }}-${{ hashFiles('fireball') }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path: fireball
