name: Build

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "src/go.mod"

      - name: Build
        run: |
          cd src
          go build -o ../fireball ./cmd

      - name: Cache fireball
        uses: actions/cache/save@v4
        with:
          path: |
            fireball
            fireball.exe
          key: ${{ runner.os }}-${{ hashFiles('fireball') }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          path: |
            fireball
            fireball.exe

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libc6-dev

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "21.1.8"

      - name: Get fireball from cache
        uses: actions/cache/restore@v4
        with:
          path: fireball
          key: ${{ runner.os }}-${{ hashFiles('fireball') }}

      - name: Run tests
        run: |
          cd tests
          ../fireball test
